name: 下午的自動化

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,login,sign,guild,answer,lottery,del_mail,logout,report,telegram,discord,line_notify,issue"
          secrets: ${{ secrets.SECRETS }}
          parameters: '{ "lottery_max_parallel": 3, "del_mail_match": [ { "title": "【勇者福利社】成功獲得抽獎資格通知信" } ], "only_failed": true }'
      - uses: gautamkrishnar/keepalive-workflow@master
