name: 下午的自動化

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@955fb50215ce7f039f2642136b341db9603e38e1
        with:
          modules: "report,ad_handler,login,sign,guild,answer,lottery,logout,report,telegram,discord,line_notify,issue"
          secrets: ${{ secrets.SECRETS }}
          parameters: '{ "lottery_max_parallel": 3 }'
      - uses: gautamkrishnar/keepalive-workflow@master
