name: 下午的自動化

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@main
        with:
          modules: "login,ad_handler,sign,report,answer,report,lottery,report,logout,report"
          parameters: ${{ secrets.parameters }}
