name: 下午的自動化

on:
    schedule:
        - cron: "30 4 * * *"

jobs:
    automation:
        name: 自動化
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/keepalive-workflow@master
            - name: Bahamut Automation
              uses: JacobLinCool/Bahamut-Automation@action
              with:
                  config: config.yml
                  secrets: ${{ secrets.SECRETS }}
