name: 下午的自動化

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@main
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          auto_sign: "true"
          auto_sign_double: "true"
          auto_draw: "true"
          auto_answer_anime: "true"
          gh_pat: ${{ secrets.GH_TOKEN }}
