name: 手動觸發的自動化 (Ubuntu)

on:
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache playwright binaries
        uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright/
            **/node_modules/playwright
          key: cache-playwright-ubuntu
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,login,sign,guild,answer,lottery,logout,report,telegram,discord,line_notify,issue"
          secrets: ${{ secrets.SECRETS }}
          parameters: '{ "lottery_max_parallel": 3 }'
