name: WIP 的自動化 (MacOS)

on:
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: ./action
        with:
          config: "config.yml"
          secrets: ${{ secrets.SECRETS }}
