name: 手動觸發的自動化

on:
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,login,sign,guild,answer,lottery,sayloud,builder,logout,report,telegram,discord,line_notify,issue"
          secrets: ${{ secrets.SECRETS }},
          browser: >
            {
              "type": "chromium"
            }
      - uses: gautamkrishnar/keepalive-workflow@master
