name: 自動化測試 Windows

on:
  workflow_dispatch:

jobs:
  automation:
    name: 自動化 Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,login,sign,logout"
          secrets: ${{ secrets.SECRETS }}
