name: 測試 builder & sayloud

on:
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@main
        with:
          modules: "login,sayloud,builder,logout"
          parameters: '{"builder":[{"bsn":"60111","snA":"120687","content":"$month$/$day$ 第一次測試"},{"bsn":"60111","snA":"120687","content":"$month$/$day$ 第二次測試"}], "sayloud":[{"to":"所有人","text":"提醒大家，今天是 $month$/$day$ 喔！"}]}'
          secrets: ${{ secrets.parameters }}
